# TWST-Core Configuration
version: 1

# Placeholder
# %twstcore_version-own%
# %player% , %player_displayName%

############### SERVER-MOTD ###############

# The maximum number of players that can play on the server.
Server-Max-Players: 20

Server-MOTD:
  Line-1: '&6--------- &bServer Name &7| &eServer MOTD &6---------'
  Line-2: '              &eSupport &dPlaceholderAPI&e!'
Maintenance-MOTD:
  Line-1: '&6--------- &bServer Name &7| &cMaintenance MOTD &6---------'
  Line-2: '              &eSupport &dPlaceholderAPI&e!'

############### JOIN-MOTD ###############

Join-MOTD:
  - "&e&m-----------------------------------------------------"
  - "&bWelcome to the server &d%player%&b!"
  - "&dwww.yourserver.com"
  - "&e&m-----------------------------------------------------"

############### JOIN_LEAVE ###############

First-Join: "&dThe player &b%player% &dhas joined for the first time!"

Groups:
  default:
    Permission: twstcore.group.default  # Make sure the player has this permission.
    Join-Message: "&7[&a+&7] &bThe player &a%player% &bhas Join the game! &d[&bDefault&d]"  # Join Message
    Leave-Message: "&7[&a-&7] &bThe player &a%player% &bhas Left the game! &d[&bDefault&d]"    # Leave Message
    Sound: ENTITY_PLAYER_LEVELUP, 1, 1 # All the sound list at https://helpch.at/docs/
    Commands: # [player] run by the player, [console] run from the console.
      - "[console] Welcome %player% to the server!"
  group1:
    Permission: twstcore.group.group1
    Join-Message: "&7[&a+&7] &bThe player &a%player% &bhas Join the game! &d[&bGroup1&d]"
    Leave-Message: "&7[&a-&7] &bThe player &a%player% &bhas Left the game! &d[&bGroup1&d]"
    Sound: ENTITY_PLAYER_LEVELUP, 1, 1
    Commands: 
      - "[console] Welcome Group1 %player% to the server!"

############### FIREWORK ###############

# Color List
# AQUA, BLACK, BLUE, FUCHSIA, GRAY, GREEN, LIME, MAROON, NAVY, OLIVE, ORANGE, PURPLE, RED, SILVER, TEAL, WHITE, YELLOW

Join-firework:
  instant-explode: false
  amount: 3
  firework-height: 3
  power: 1
  type: BALL
  flicker: false
  trail: false
  colors:
    - YELLOW
  fade:
    - WHITE

############### TOGGLE FLY ###############
Toggle-Fly:
  Enable-World:
    - "world"
    - "world_nether"
    - "world_the_end"

  Format:
    Enabled: "&aEnabled"
    Disabled: "&cDisabled"