# TWST-Core Configuration
version: 1

# Placeholder
# %twstcore_version-own%
# %player% , %player_displayName%

Join-MOTD:
  - "&e&m-----------------------------------------------------"
  - "&bWelcome to the server &d%player%&b!"
  - "&awww.yourserver.com"
  - "&e&m-----------------------------------------------------"

First-Join: "&dThe player &b%player% &dhas joined for the first time!"

Groups:
  group1:
    Permission: twstcore.group.group1  # Make sure the player has this permission.
    Join-Message: "&7[&a+&7] &bThe player &a%player% &bhas Join the game! &d[&bGroup1&d]"  # Join Message
    Leave-Message: "&7[&a-&7] &bThe player &a%player% &bhas Left the game! &d[&bGroup1&d]"    # Leave Message
    Sound: BLOCK_NOTE_BLOCK_CHIME # go to https://helpch.at/docs/ ,select your server version and go to Bukkit.Sound then found it.
    Commands: # [player] run by the player, [console] run from the console.
      - "[console] This is Example 1!"

# Color List
# AQUA, BLACK, BLUE, FUCHSIA, GRAY, GREEN, LIME, MAROON, NAVY, OLIVE, ORANGE, PURPLE, RED, SILVER, TEAL, WHITE, YELLOW

Join-firework:
  instant-explode: false
  amount: 3
  firework-height: 3
  power: 1
  type: BALL
  flicker: false
  trail: false
  colors:
    - YELLOW
  fade:
    - WHITE