name: TWST-Core
author: CloudOcean
version: '${project.version}'
main: me.thecatisbest.awa.Main
api-version: 1.13
depend: [LuckPerms]
softdepend: [PlaceholderAPI, MBedwars]
commands:
  twstcore:
    description: twst core plugin main command