name: TWST-Core
author: thecatisbest
version: '${project.version}'
main: me.thecatisbest.awa.Main
api-version: 1.13
softdepend: [PlaceholderAPI]
commands:
  twstcore:
    aliases: [twst]
    description: twst core plugin main command

  helpful:
    description: helpful command.